In [1]:
import pandas as pd

In [3]:
cars_data = pd.read_csv("car-sales.csv")

# Selecting and Viewing Data

In [11]:
# This will select starting or initial rows from given data but default value of no. of rows is 5
cars_data.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [10]:
# This will select last or final rows from given data but default value of no. of rows is 5
cars_data.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [16]:
animals = pd.Series(["Lion", "Monkey", "Dog", "Elephant", "Leopard"], index=[0,3,5,8,3])
animals

0        Lion
3      Monkey
5         Dog
8    Elephant
3     Leopard
dtype: object

##### # .loc : is for index

In [15]:
animals.loc[3]

3     Monkey
3    Leopard
dtype: object

In [22]:
animals.loc[:8:2]

0    Lion
5     Dog
dtype: object

##### # .iloc : is for position

In [25]:
animals.iloc[3]

'Elephant'

In [26]:
# Slicing with iloc
animals.iloc[:5:2]

0       Lion
5        Dog
3    Leopard
dtype: object

##### Viewing Column

In [31]:
# Below both methods are correct to view data
cars_data.Make, cars_data["Odometer (KM)"]

(0    Toyota
 1     Honda
 2    Toyota
 3       BMW
 4    Nissan
 5    Toyota
 6     Honda
 7     Honda
 8    Toyota
 9    Nissan
 Name: Make, dtype: object,
 0    150043
 1     87899
 2     32549
 3     11179
 4    213095
 5     99213
 6     45698
 7     54738
 8     60000
 9     31600
 Name: Odometer (KM), dtype: int64)

##### Viewing data using condition

In [34]:
cars_data[cars_data["Odometer (KM)"]>87899]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00
5  Toyota  Green          99213      4  $4,500.00