# Data Manipulation

In [1]:
import pandas as pd
import numpy as np

In [2]:
cars_data = pd.read_csv("car-sales.csv")
cars_data

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

##### Convert whole data in Make column into lowercase

In [3]:
cars_data["Make"]=cars_data["Make"].str.lower()
cars_data

     Make Colour  Odometer (KM)  Doors       Price
0  toyota  White         150043      4   $4,000.00
1   honda    Red          87899      4   $5,000.00
2  toyota   Blue          32549      3   $7,000.00
3     bmw  Black          11179      5  $22,000.00
4  nissan  White         213095      4   $3,500.00
5  toyota  Green          99213      4   $4,500.00
6   honda   Blue          45698      4   $7,500.00
7   honda   Blue          54738      4   $7,000.00
8  toyota  White          60000      4   $6,250.00
9  nissan  White          31600      4   $9,700.00

In [4]:
car_missing = pd.read_csv("car-sales-missing-data.csv")
car_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

##### Filling missing value in car_missing

In [5]:
car_missing["Odometer"]=car_missing["Odometer"].fillna(car_missing["Odometer"].mean())
car_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

##### This will drop all the rows containing any missing value

In [6]:
car_missing.dropna(inplace=True)
car_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

##### Saving data whose all columns are filled as car_data_dropped.csv

In [7]:
car_missing = pd.read_csv("car-sales-missing-data.csv")
car_missing_dropped=car_missing.dropna()
car_missing_dropped.to_csv("car_data_dropped.csv")
car_missing_dropped

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500

##### Adding New Column in cars_data

In [8]:
# Using Series
seat_column = pd.Series([5,7,5,7,5,7])
cars_data["No. of Seats"]=seat_column
cars_data

     Make Colour  Odometer (KM)  Doors       Price  No. of Seats
0  toyota  White         150043      4   $4,000.00           5.0
1   honda    Red          87899      4   $5,000.00           7.0
2  toyota   Blue          32549      3   $7,000.00           5.0
3     bmw  Black          11179      5  $22,000.00           7.0
4  nissan  White         213095      4   $3,500.00           5.0
5  toyota  Green          99213      4   $4,500.00           7.0
6   honda   Blue          45698      4   $7,500.00           NaN
7   honda   Blue          54738      4   $7,000.00           NaN
8  toyota  White          60000      4   $6,250.00           NaN
9  nissan  White          31600      4   $9,700.00           NaN

In [9]:
cars_data["No. of Seats"].fillna(5,inplace=True)
cars_data

C:\Users\asus\AppData\Local\Temp\ipykernel_13704\3599577014.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["No. of Seats"].fillna(5,inplace=True)

     Make Colour  Odometer (KM)  Doors       Price  No. of Seats
0  toyota  White         150043      4   $4,000.00           5.0
1   honda    Red          87899      4   $5,000.00           7.0
2  toyota   Blue          32549      3   $7,000.00           5.0
3     bmw  Black          11179      5  $22,000.00           7.0
4  nissan  White         213095      4   $3,500.00           5.0
5  toyota  Green          99213      4   $4,500.00           7.0
6   honda   Blue          45698      4   $7,500.00           5.0
7   honda   Blue          54738      4   $7,000.00           5.0
8  toyota  White          60000      4   $6,250.00           5.0
9  nissan  White          31600      4   $9,700.00           5.0

In [10]:
# Using Python List
Mileage=[16.9,15,19,13,8,17,15,16.6,20,15.9]
cars_data["Mileage"]=Mileage
cars_data

     Make Colour  Odometer (KM)  Doors       Price  No. of Seats  Mileage
0  toyota  White         150043      4   $4,000.00           5.0     16.9
1   honda    Red          87899      4   $5,000.00           7.0     15.0
2  toyota   Blue          32549      3   $7,000.00           5.0     19.0
3     bmw  Black          11179      5  $22,000.00           7.0     13.0
4  nissan  White         213095      4   $3,500.00           5.0      8.0
5  toyota  Green          99213      4   $4,500.00           7.0     17.0
6   honda   Blue          45698      4   $7,500.00           5.0     15.0
7   honda   Blue          54738      4   $7,000.00           5.0     16.6
8  toyota  White          60000      4   $6,250.00           5.0     20.0
9  nissan  White          31600      4   $9,700.00           5.0     15.9

In [11]:
cars_data["Fuel Used"]=(cars_data["Odometer (KM)"]/cars_data["Mileage"])
cars_data

,Make,Colour,Odometer (KM),Doors,Price,No. of Seats,Mileage,Fuel Used
0,toyota,White,150043,4,"$4,000.00",5.0,16.9,8878.284024
1,honda,Red,87899,4,"$5,000.00",7.0,15.0,5859.933333
2,toyota,Blue,32549,3,"$7,000.00",5.0,19.0,1713.105263
3,bmw,Black,11179,5,"$22,000.00",7.0,13.0,859.923077
4,nissan,White,213095,4,"$3,500.00",5.0,8.0,26636.875000
5,toyota,Green,99213,4,"$4,500.00",7.0,17.0,5836.058824
6,honda,Blue,45698,4,"$7,500.00",5.0,15.0,3046.533333
7,honda,Blue,54738,4,"$7,000.00",5.0,16.6,3297.469880
8,toyota,White,60000,4,"$6,250.00",5.0,20.0,3000.000000
9,nissan,White,31600,4,"$9,700.00",5.0,15.9,1987.421384

In [12]:
# Create column with single value
cars_data["Wheels"] = 4
cars_data

,Make,Colour,Odometer (KM),Doors,Price,No. of Seats,Mileage,Fuel Used,Wheels
0,toyota,White,150043,4,"$4,000.00",5.0,16.9,8878.284024,4
1,honda,Red,87899,4,"$5,000.00",7.0,15.0,5859.933333,4
2,toyota,Blue,32549,3,"$7,000.00",5.0,19.0,1713.105263,4
3,bmw,Black,11179,5,"$22,000.00",7.0,13.0,859.923077,4
4,nissan,White,213095,4,"$3,500.00",5.0,8.0,26636.875000,4
5,toyota,Green,99213,4,"$4,500.00",7.0,17.0,5836.058824,4
6,honda,Blue,45698,4,"$7,500.00",5.0,15.0,3046.533333,4
7,honda,Blue,54738,4,"$7,000.00",5.0,16.6,3297.469880,4
8,toyota,White,60000,4,"$6,250.00",5.0,20.0,3000.000000,4
9,nissan,White,31600,4,"$9,700.00",5.0,15.9,1987.421384,4

##### Droping column

In [13]:
cars_data.drop("Wheels",axis=1,inplace=True)
cars_data

,Make,Colour,Odometer (KM),Doors,Price,No. of Seats,Mileage,Fuel Used
0,toyota,White,150043,4,"$4,000.00",5.0,16.9,8878.284024
1,honda,Red,87899,4,"$5,000.00",7.0,15.0,5859.933333
2,toyota,Blue,32549,3,"$7,000.00",5.0,19.0,1713.105263
3,bmw,Black,11179,5,"$22,000.00",7.0,13.0,859.923077
4,nissan,White,213095,4,"$3,500.00",5.0,8.0,26636.875000
5,toyota,Green,99213,4,"$4,500.00",7.0,17.0,5836.058824
6,honda,Blue,45698,4,"$7,500.00",5.0,15.0,3046.533333
7,honda,Blue,54738,4,"$7,000.00",5.0,16.6,3297.469880
8,toyota,White,60000,4,"$6,250.00",5.0,20.0,3000.000000
9,nissan,White,31600,4,"$9,700.00",5.0,15.9,1987.421384

### Apply Function

In [14]:
cars_data["Odometer (KM)"]=cars_data["Odometer (KM)"].apply(lambda x : x / 1.6)
cars_data

,Make,Colour,Odometer (KM),Doors,Price,No. of Seats,Mileage,Fuel Used
0,toyota,White,93776.875,4,"$4,000.00",5.0,16.9,8878.284024
1,honda,Red,54936.875,4,"$5,000.00",7.0,15.0,5859.933333
2,toyota,Blue,20343.125,3,"$7,000.00",5.0,19.0,1713.105263
3,bmw,Black,6986.875,5,"$22,000.00",7.0,13.0,859.923077
4,nissan,White,133184.375,4,"$3,500.00",5.0,8.0,26636.875000
5,toyota,Green,62008.125,4,"$4,500.00",7.0,17.0,5836.058824
6,honda,Blue,28561.250,4,"$7,500.00",5.0,15.0,3046.533333
7,honda,Blue,34211.250,4,"$7,000.00",5.0,16.6,3297.469880
8,toyota,White,37500.000,4,"$6,250.00",5.0,20.0,3000.000000
9,nissan,White,19750.000,4,"$9,700.00",5.0,15.9,1987.421384